max_len: 20
model_params:
  num_classes: 327
  batch_size: 64
  embedding_size: 300
  hidden_size: 256
  epochs: 20  # amsoftmax需要25个epoch，其它需要20个epoch
  learning_rate: 0.001
  keep_prob: 0.5
  kernel_size: 2
  num_filters: 128


data_params:
  min_count: 5
#  data_path: 'Z:\Corpus\TrainingCorpus\amsoftmax\train.csv'
  data_path: './data/without_testdata.csv'
#  val_path: 'Z:\Corpus\TrainingCorpus\amsoftmax\val.csv'
  val_path: './data/eval.csv'
ckpt_file: './model_margin0.3_dropout0.5_remove_test_bert/'
embedding_path: 'Z:/Models/词向量/xyz-w2v.json'
use_embedding: False

gpu_id: '0,1'
